#!/usr/bin/env python
import os,sys

list_dirs = os.listdir(".")
selected_dirs =[]
for dir in list_dirs :
  if ( dir.find("crab") != -1 ) :
    selected_dirs.append( dir )

for dir in selected_dirs :
  cmd = "crab status -d %s"%(dir)
  os.system(cmd)

